### ISSUE TITLE
☂️ Suspense umbrella task

### ISSUE THREAD

**Issue by bvaughn** [facebook/react-devtools#1189]
## Misc
- [ ] Keyboard navigation: Arrow key navigation for selected element is a bit broken. You can use down/right arrow to drill down into a `Suspense` component, but the up/left arrows won't drill back up. (It gets stuck at the component beneath `Suspense`.)
![arrowkey](https://user-images.githubusercontent.com/29597/47247233-4f6fc100-d3b7-11e8-83a1-2601787e6867.gif)

## Hiding timed-out children

facebook/react/pull/13823 changed the behavior of timed-out suspense trees. In order to preserve state (of both React components and host components) the timed-out tree now stays mounted, but gets hidden (e.g. "display: none").

For the GIF below, I used `create-react-app` with the following changes: https://gist.github.com/bvaughn/aab2a855c5fa1daa9ca55b1fdfac20a5

- [ ] If the suspended subtree is expanded in the DevTools tree view, it gets auto-collapsed when it's hidden.
![collapse](https://user-images.githubusercontent.com/29597/47247260-6dd5bc80-d3b7-11e8-8a21-f179b290b537.gif)

- [ ] The Profiler's render counter gets reset for all components in the hidden subtree. This makes it look like it's a new tree and might be confusing to people.

## Testing 

**TODO** @bvaughn and @acdlite will fill this in later.

**Comment by sw-yx** [comment]
would this be a nice to have? https://github.com/facebook/react-devtools/issues/1141

**Comment by bvaughn** [comment]
Not sure. DevTools is already monstrously large. Don't know how I feel about adding more panels and increasing scope until/unless we tackle something like #1214

**Comment by bvaughn** [comment]
Fixes went out with 3.4.3
