### ISSUE TITLE
Themes follow up work

### ISSUE THREAD

**Issue by bvaughn** [facebook/react-devtools#705]
Related to PRs #698 and #718, issue #108.

### Followups from Dan

- [x] Fix live state updates; regressed in 90896c9 (see [here](https://github.com/facebook/react-devtools/pull/718#issuecomment-301326181)) (PR #721)
- [x] Tweak dark theme selection colors (see [here](https://github.com/facebook/react-devtools/pull/718#issuecomment-301324534)) (PR #722)
- [x] Add better padding to "_Unable to find React on page_" interstitial text (see [here](https://github.com/facebook/react-devtools/pull/718#issuecomment-301326276)). (PR #731)
- [x] Dan can't press settings button in Firefox 47.0.1 (PR #719)
- [x] Also sees Chrome team there instead of FF theme (PR #720)
- [x] The HTML headers are jarring. Can we get rid of HTML shells and always let Panel render headers, even if shells declare the text? (PR #731)

### Better default theme behavior

- [x] As of Chrome 54 the property `chrome.devtools.panels.themeName` should contain values "default" or "dark". It would be nice for the default devtools theme to have a dark variation as well that is automatically used if the value is "dark". (If a user selects a theme _other than_ default this behavior should not apply.)
- [x] There is active discussion on how to expose this feature to add-ons in Firefox as well (see [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1349896)). Once this settles down it would be nice for the Firefox add-on to implement the same behavior as Chrome. (#802)

### Remove selected component header in detail pane

- [x] There is no equivalent in Chrome or Firefox devtools and the bright-blue active highlight makes it apparent what's selected anyway. We could gain back a lot of vertical space by removing it (>40px) that would be better used by the props/values themselves. (This item came as feedback from @sebmarkbage and @vjeux.)

**Comment by bvaughn** [comment]
First step, I've created 2 new themes and made a couple of minor modifications that I think will enable us to roughly approximate the themes used by Chrome and Firefox. Screenshots~
### Chrome (light)
<img width="951" alt="screen shot 2017-05-10 at 7 26 24 pm" src="https://cloud.githubusercontent.com/assets/29597/25929685/bf99d39e-35b6-11e7-96e6-4409fd390bab.png">

### Chrome (dark)
<img width="1030" alt="screen shot 2017-05-10 at 7 26 57 pm" src="https://cloud.githubusercontent.com/assets/29597/25929684/bf98c9ae-35b6-11e7-9a3e-773036e13550.png">

### Firefox (dark)
<img width="949" alt="screen shot 2017-05-10 at 7 25 52 pm" src="https://cloud.githubusercontent.com/assets/29597/25929683/bf8d8a58-35b6-11e7-8981-b92621075d5a.png">

**Comment by bvaughn** [comment]
Devtools "default" theme now follows Chrome's "default" vs "dark" preference!

![devtools-theme-toggle-chrome](https://cloud.githubusercontent.com/assets/29597/25931698/c82ce206-35c2-11e7-8bff-86c53d56d38d.gif)

**Comment by bvaughn** [comment]
Most of this work has been completed. Keeping the issue open until the next Firefox version launches and I've addressed the last remaining point for light/dark Firefox themes.

**Comment by gaearon** [comment]
Added a few followups from https://github.com/facebook/react-devtools/pull/718.

**Comment by bvaughn** [comment]
>The HTML headers are jarring. Can we get rid of HTML shells and always let Panel render headers, even if shells declare the text?

Could you clarify what you mean?

I _think_ you're saying that the headers declared in `panel.html` and `run.js` (the ones without a "style" really) don't fit in as well as the others and you'd like to move them into the app. Is this right? Screenshots if not?

**Comment by gaearon** [comment]
>I think you're saying that the headers declared in panel.html and run.js (the ones without a "style" really) don't fit in as well as the others and you'd like to move them into the app. Is this right? Screenshots if not?

Yes. Basically I'd like to get rid of all HTML UI that we have.

**Comment by clarkbw** [comment]
The code for devtools.panels.themeName in Firefox, aka [bug 1349896](https://bugzilla.mozilla.org/show_bug.cgi?id=1349896#c55) just landed and so it should be in tomorrow's [Nightly](http://nightly.mozilla.org/).  I'll check for it and update here when its been verified.

**Comment by bvaughn** [comment]
Nice! I've been checking it every other day. Super exciting. 😁 Thanks for the update!

**Comment by clarkbw** [comment]
Ok, I've been playing with it in Nightly and it works great!  This API is shipping with Firefox 55 (currently Nightly) which will be available to release on August 8th.

You can access the theme name at any point via:

```js
if (chrome.devtools.panels.themeName) {
  console.log(chrome.devtools.panels.themeName);
}
```

We've also implemented a listener that will receive updates when the theme has been changed:

```js
if (chrome.devtools.panels.onThemeChanged) {
  chrome.devtools.panels.onThemeChanged.addListener(themeName => {
    console.log('theme changed', themeName);
  });
}
```

The possible themeName values are `light`, `dark`, and `firebug`.

💃

**Comment by bvaughn** [comment]
Thanks for the update Bryan!

I didn't build a Firefox+firebug theme. I was tentatively planning on just switching between light and dark, unless someone else wants to build one? 😁 

I'm going to try to land #751 soon b'c it tidies stuff up a bit more, and then we can tackle the Firefox TODO and maybe ship support for it in 2.3.0?

**Comment by clarkbw** [comment]
> I didn't build a Firefox+firebug theme. I was tentatively planning on just switching between light and dark, unless someone else wants to build one? 😁

Sounds good!  We can ask if the firebug community wants to contribute that.

> I'm going to try to land #751 soon b'c it tidies stuff up a bit more, and then we can tackle the Firefox TODO and maybe ship support for it in 2.3.0?

👍

**Comment by bvaughn** [comment]
Closed via #802
