### ISSUE TITLE
Fix RN style editor

### ISSUE THREAD

**Issue by gaearon** [facebook/react-devtools#759]
Let's just fix all of these. It can't be too hard.

#### Done (needing review)
- [x] #761: RN style editor doesn't work with themes
- [x] #762: Editing RTCView properties produces redbox on Fiber
- [x] #762: Editing RTCView properties doesn't update DevTools UI (both Stack and Fiber)
- [x] #762: Remove style by deleting property name
- [x] #765: It's too hard to click into the value field of a newly created style before any text is entered.
- [x] https://github.com/facebook/react-devtools/pull/770 and https://github.com/facebook/react-native/pull/14290 Sometimes, the Inspect tool fails to select certain UI bits (eg Catalyst app main "Search" input). Mentioned [here](https://github.com/facebook/react-devtools/pull/762#issuecomment-305310100).

**Comment by gaearon** [comment]
https://github.com/facebook/react-devtools/pull/762

**Comment by bvaughn** [comment]
#761
